name: drawing_board
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_base_architecture_plugin:
    git:
      url: https://github.com/sagarkudecha223/flutter_base_architecture_plugin.git
      ref: development

  shared_preferences: 2.5.3
  go_router: 15.2.3
  cupertino_icons: 1.0.8
  gap: 3.0.1
  sizer: 3.0.5
  flutter_animate: 4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  kiwi_generator:
  built_value_generator:

flutter:

  uses-material-design: true

#  assets:
#    - assets/images/


#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/poppins.ttf